/**
 * Copyright (c) 2026 J.P.J. Bloemscheer / JeroenTechSolutions
 * Licensed under the EUPL-1.2 (see LICENSE.txt)
 *
 * Unit tests for the SVG renderer. POINT only in v1.
 *
 * Assertions are regex-on-string -- the output is generated by us and
 * deterministic, so regex against specific attributes pins facts
 * (cx, cy, viewBox shape, namespace presence) without locking the
 * full document string. This is structurally targeted, not snapshot.
 */
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';

import { calculateBoundingBox, renderToSvg } from '../src/wkt/renderer.js';

function svgFor(x: number, y: number): string {
  return renderToSvg({ type: 'Point', coordinates: [x, y] });
}

function viewBoxOf(svg: string): [number, number, number, number] {
  const m = svg.match(/viewBox="([^"]+)"/);
  assert.ok(m, 'svg must have a viewBox attribute');
  const parts = m[1].split(/\s+/).map(Number);
  assert.equal(parts.length, 4, 'viewBox must be four numbers');
  return parts as [number, number, number, number];
}

describe('renderToSvg: POINT', () => {
  it('produces a self-contained <svg> document with the SVG namespace', () => {
    const svg = svgFor(10, 20);
    assert.match(svg, /^<\?xml version="1\.0"/);
    assert.match(svg, /<svg[^>]*xmlns="http:\/\/www\.w3\.org\/2000\/svg"/);
    assert.match(svg, /<\/svg>\s*$/);
  });

  it('emits a <circle> at the WKT coordinates', () => {
    const svg = svgFor(10, 20);
    assert.match(svg, /<circle[^>]*\bcx="10"[^>]*\bcy="20"/);
  });

  it('handles negative coordinates', () => {
    const svg = svgFor(-5, -7.5);
    assert.match(svg, /<circle[^>]*\bcx="-5"[^>]*\bcy="-7\.5"/);
  });

  it('handles the origin', () => {
    const svg = svgFor(0, 0);
    assert.match(svg, /<circle[^>]*\bcx="0"[^>]*\bcy="0"/);
  });

  it('renders parsed scientific notation as decimal output', () => {
    // 1.5e3 → 1500, -2.5e-2 → -0.025 (after parseFloat round-trip).
    const svg = svgFor(1.5e3, -2.5e-2);
    assert.match(svg, /<circle[^>]*\bcx="1500"[^>]*\bcy="-0\.025"/);
  });

  it('produces a viewBox with strictly positive width and height', () => {
    // Degenerate single-point bbox is zero-extent; padding must lift it.
    const [, , width, height] = viewBoxOf(svgFor(10, 20));
    assert.ok(width > 0, `expected width > 0, got ${width}`);
    assert.ok(height > 0, `expected height > 0, got ${height}`);
  });

  it('centres the viewBox around the point (within the padding)', () => {
    const [vx, vy, w, h] = viewBoxOf(svgFor(100, 200));
    // The padded bbox should bracket the point on both axes.
    assert.ok(vx <= 100 && vx + w >= 100, 'point x not inside viewBox');
    assert.ok(vy <= 200 && vy + h >= 200, 'point y not inside viewBox');
  });

  it('applies a default fill so the point is visible', () => {
    const svg = svgFor(10, 20);
    assert.match(svg, /<circle[^>]*\bfill="#[0-9a-fA-F]+"/);
  });
});

describe('calculateBoundingBox', () => {
  it('returns degenerate bbox for a single point', () => {
    const bbox = calculateBoundingBox([[10, 20]]);
    assert.deepEqual(bbox, { minX: 10, minY: 20, maxX: 10, maxY: 20 });
  });

  it('walks every coord to find tight extents', () => {
    const bbox = calculateBoundingBox([
      [10, 20],
      [-5, 100],
      [3, -7],
    ]);
    assert.deepEqual(bbox, { minX: -5, minY: -7, maxX: 10, maxY: 100 });
  });

  it('throws on empty input', () => {
    assert.throws(() => calculateBoundingBox([]), /at least one coordinate/);
  });
});
