/**
 * Copyright (c) 2026 J.P.J. Bloemscheer / JeroenTechSolutions
 * Licensed under the EUPL-1.2 (see LICENSE.txt)
 *
 * Unit tests for the SVG renderer. POINT only in v1.
 *
 * Assertions are regex-on-string -- the output is generated by us and
 * deterministic, so regex against specific attributes pins facts
 * (cx, cy, viewBox shape, namespace presence) without locking the
 * full document string. This is structurally targeted, not snapshot.
 */
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';

import { calculateBoundingBox, renderToSvg } from '../src/wkt/renderer.js';

function svgFor(x: number, y: number): string {
  return renderToSvg({ type: 'Point', coordinates: [x, y] });
}

function viewBoxOf(svg: string): [number, number, number, number] {
  const m = svg.match(/viewBox="([^"]+)"/);
  assert.ok(m, 'svg must have a viewBox attribute');
  const parts = m[1].split(/\s+/).map(Number);
  assert.equal(parts.length, 4, 'viewBox must be four numbers');
  return parts as [number, number, number, number];
}

describe('renderToSvg: POINT', () => {
  it('produces a self-contained <svg> document with the SVG namespace', () => {
    const svg = svgFor(10, 20);
    assert.match(svg, /^<\?xml version="1\.0"/);
    assert.match(svg, /<svg[^>]*xmlns="http:\/\/www\.w3\.org\/2000\/svg"/);
    assert.match(svg, /<\/svg>\s*$/);
  });

  it('emits a <circle> at the WKT coordinates', () => {
    const svg = svgFor(10, 20);
    assert.match(svg, /<circle[^>]*\bcx="10"[^>]*\bcy="20"/);
  });

  it('handles negative coordinates', () => {
    const svg = svgFor(-5, -7.5);
    assert.match(svg, /<circle[^>]*\bcx="-5"[^>]*\bcy="-7\.5"/);
  });

  it('handles the origin', () => {
    const svg = svgFor(0, 0);
    assert.match(svg, /<circle[^>]*\bcx="0"[^>]*\bcy="0"/);
  });

  it('renders parsed scientific notation as decimal output', () => {
    // 1.5e3 → 1500, -2.5e-2 → -0.025 (after parseFloat round-trip).
    const svg = svgFor(1.5e3, -2.5e-2);
    assert.match(svg, /<circle[^>]*\bcx="1500"[^>]*\bcy="-0\.025"/);
  });

  it('produces a viewBox with strictly positive width and height', () => {
    // Degenerate single-point bbox is zero-extent; padding must lift it.
    const [, , width, height] = viewBoxOf(svgFor(10, 20));
    assert.ok(width > 0, `expected width > 0, got ${width}`);
    assert.ok(height > 0, `expected height > 0, got ${height}`);
  });

  it('centres the viewBox around the point (within the padding)', () => {
    const [vx, vy, w, h] = viewBoxOf(svgFor(100, 200));
    // The padded bbox should bracket the point on both axes.
    assert.ok(vx <= 100 && vx + w >= 100, 'point x not inside viewBox');
    assert.ok(vy <= 200 && vy + h >= 200, 'point y not inside viewBox');
  });

  it('applies a default fill so the point is visible', () => {
    const svg = svgFor(10, 20);
    assert.match(svg, /<circle[^>]*\bfill="#[0-9a-fA-F]+"/);
  });

  it('uses vector-effect="non-scaling-stroke" so the stroke is visible at any viewBox scale', () => {
    // Regression guard: without this, a multi-km bbox (e.g. a real
    // ProRail alignment) renders the polyline at sub-pixel stroke
    // width and the SVG appears empty in the browser.
    const svg = svgFor(10, 20);
    assert.match(svg, /<circle[^>]*\bvector-effect="non-scaling-stroke"/);
  });
});

describe('renderToSvg: LINESTRING', () => {
  it('emits a <polyline> with the coordinate list', () => {
    const svg = renderToSvg({
      type: 'LineString',
      coordinates: [[0, 0], [10, 5], [20, 0]],
    });
    assert.match(svg, /<polyline\b[^>]*\bpoints="0,0 10,5 20,0"/);
  });

  it('uses fill="none" so the polyline does not auto-fill', () => {
    const svg = renderToSvg({
      type: 'LineString',
      coordinates: [[0, 0], [10, 0]],
    });
    assert.match(svg, /<polyline\b[^>]*\bfill="none"/);
  });

  it('pins the stroke to screen pixels via vector-effect="non-scaling-stroke"', () => {
    const svg = renderToSvg({
      type: 'LineString',
      coordinates: [[0, 0], [10000, 5000]],
    });
    assert.match(svg, /<polyline\b[^>]*\bvector-effect="non-scaling-stroke"/);
  });

  it('produces a viewBox that brackets every coordinate', () => {
    const svg = renderToSvg({
      type: 'LineString',
      coordinates: [[0, 0], [100, 50]],
    });
    const [vx, vy, w, h] = viewBoxOf(svg);
    assert.ok(vx <= 0 && vx + w >= 100, 'x extent must cover [0, 100]');
    assert.ok(vy <= 0 && vy + h >= 50, 'y extent must cover [0, 50]');
  });

  it('wraps the polyline in a Y-flipping <g transform>', () => {
    const svg = renderToSvg({
      type: 'LineString',
      coordinates: [[0, 0], [10, 5]],
    });
    assert.match(svg, /<g[^>]*transform="translate\(0, [^)]+\) scale\(1, -1\)"/);
  });
});

describe('renderToSvg: TRIANGLE', () => {
  it('emits a <polygon> using only the 3 unique corners (closing repeat dropped)', () => {
    const svg = renderToSvg({
      type: 'Triangle',
      coordinates: [[0, 0], [1, 0], [0, 1], [0, 0]],
    });
    assert.match(svg, /<polygon\b[^>]*\bpoints="0,0 1,0 0,1"/);
  });

  it('applies a fill so the interior is visible', () => {
    const svg = renderToSvg({
      type: 'Triangle',
      coordinates: [[0, 0], [1, 0], [0, 1], [0, 0]],
    });
    assert.match(svg, /<polygon\b[^>]*\bfill="rgba\([^)]+\)"/);
  });

  it('pins the polygon stroke via vector-effect="non-scaling-stroke"', () => {
    const svg = renderToSvg({
      type: 'Triangle',
      coordinates: [[0, 0], [10000, 0], [5000, 8000], [0, 0]],
    });
    assert.match(svg, /<polygon\b[^>]*\bvector-effect="non-scaling-stroke"/);
  });

  it('produces a viewBox that brackets every corner', () => {
    const svg = renderToSvg({
      type: 'Triangle',
      coordinates: [[-2, -3], [4, 0], [0, 5], [-2, -3]],
    });
    const [vx, vy, w, h] = viewBoxOf(svg);
    assert.ok(vx <= -2 && vx + w >= 4, 'x extent must cover [-2, 4]');
    assert.ok(vy <= -3 && vy + h >= 5, 'y extent must cover [-3, 5]');
  });
});

describe('renderToSvg: TIN', () => {
  it('emits one <polygon> per triangle', () => {
    const svg = renderToSvg({
      type: 'Tin',
      triangles: [
        [[0, 0], [1, 0], [0, 1], [0, 0]],
        [[1, 0], [1, 1], [0, 1], [1, 0]],
      ],
    });
    const polygons = svg.match(/<polygon\b/g) ?? [];
    assert.equal(polygons.length, 2);
  });

  it('drops the closing-repeat coord on each triangle', () => {
    const svg = renderToSvg({
      type: 'Tin',
      triangles: [[[0, 0], [10, 0], [5, 10], [0, 0]]],
    });
    assert.match(svg, /<polygon\b[^>]*\bpoints="0,0 10,0 5,10"/);
  });

  it('produces a viewBox that brackets every vertex of every triangle', () => {
    const svg = renderToSvg({
      type: 'Tin',
      triangles: [
        [[0, 0], [10, 0], [5, 10], [0, 0]],
        [[10, 0], [10, -5], [5, -5], [10, 0]],
      ],
    });
    const [vx, vy, w, h] = viewBoxOf(svg);
    assert.ok(vx <= 0 && vx + w >= 10, 'x extent must cover [0, 10]');
    assert.ok(vy <= -5 && vy + h >= 10, 'y extent must cover [-5, 10]');
  });
});

describe('renderToSvg: CIRCULARSTRING', () => {
  it('emits a single <polyline> approximating the arc', () => {
    const svg = renderToSvg({
      type: 'CircularString',
      coordinates: [[1, 0], [0, 1], [-1, 0]],
    });
    const polylines = svg.match(/<polyline\b/g) ?? [];
    assert.equal(polylines.length, 1);
  });

  it('viewBox brackets the full arc extent', () => {
    const svg = renderToSvg({
      type: 'CircularString',
      coordinates: [[1, 0], [0, 1], [-1, 0]],
    });
    const [vx, vy, w, h] = viewBoxOf(svg);
    assert.ok(vx <= -1 && vx + w >= 1, 'x extent must cover [-1, 1]');
    assert.ok(vy <= 0 && vy + h >= 1, 'y extent must cover [0, 1]');
  });
});

describe('renderToSvg: COMPOUNDCURVE with CLOTHOID', () => {
  it('emits exactly one <polyline> spanning all members', () => {
    const svg = renderToSvg({
      type: 'CompoundCurve',
      members: [
        { type: 'LineString', coordinates: [[0, 0], [100, 0]] },
        { type: 'Clothoid', startKappa: 0, endKappa: 0.005, length: 48 },
      ],
    });
    const polylines = svg.match(/<polyline\b/g) ?? [];
    assert.equal(polylines.length, 1);
  });

  it('clothoid section ends near the JTS analytical reference (47.93 + 100, 1.92)', () => {
    const svg = renderToSvg({
      type: 'CompoundCurve',
      members: [
        { type: 'LineString', coordinates: [[0, 0], [100, 0]] },
        { type: 'Clothoid', startKappa: 0, endKappa: 0.005, length: 48 },
      ],
    });
    const m = svg.match(/<polyline[^>]*\bpoints="([^"]+)"/);
    assert.ok(m, 'expected a polyline');
    const points = m[1].split(' ').map((p) => p.split(',').map(Number));
    const last = points[points.length - 1];
    // Reference: clothoid end at (47.93, 1.92) RELATIVE to clothoid start (100, 0)
    // → absolute (147.93, 1.92).
    assert.ok(Math.abs(last[0] - 147.93) < 0.01, `x = ${last[0]}`);
    assert.ok(Math.abs(last[1] - 1.92) < 0.01, `y = ${last[1]}`);
  });

  it('rail-bend chain (line + clothoid + arc + clothoid + line) is one polyline', () => {
    const svg = renderToSvg({
      type: 'CompoundCurve',
      members: [
        { type: 'LineString', coordinates: [[0, 0], [100, 0]] },
        { type: 'Clothoid', startKappa: 0, endKappa: 0.005, length: 48 },
        {
          type: 'CircularString',
          coordinates: [[147.93, 1.92], [200, 50], [150, 100]],
        },
        { type: 'Clothoid', startKappa: 0.005, endKappa: 0, length: 48 },
        { type: 'LineString', coordinates: [[150, 100], [50, 200]] },
      ],
    });
    const polylines = svg.match(/<polyline\b/g) ?? [];
    assert.equal(polylines.length, 1);
  });
});

describe('calculateBoundingBox', () => {
  it('returns degenerate bbox for a single point', () => {
    const bbox = calculateBoundingBox([[10, 20]]);
    assert.deepEqual(bbox, { minX: 10, minY: 20, maxX: 10, maxY: 20 });
  });

  it('walks every coord to find tight extents', () => {
    const bbox = calculateBoundingBox([
      [10, 20],
      [-5, 100],
      [3, -7],
    ]);
    assert.deepEqual(bbox, { minX: -5, minY: -7, maxX: 10, maxY: 100 });
  });

  it('throws on empty input', () => {
    assert.throws(() => calculateBoundingBox([]), /at least one coordinate/);
  });
});
